FROM golang:1.12.0-alpine3.9
RUN mkdir /app
ADD . /app
WORKDIR /app

# pull application dependencies before build
RUN go mod download

# build the application
RUN go build -o main .

# execute the binary at container start
CMD ["/app/main"]
